### ISSUE TITLE
Comparison to existing log shippers

### ISSUE THREAD

**Issue by asafm** [pinterest/singer#1]
Open source log shippers exists: FileBeat, Telegraph, FluentD.
What the difference between each to Singer?
Can this be written in Readme?

**Comment by ambud** [comment]
Scribed and Fluentd would probably be closer to Singer than FileBeat and Telegraph primarily due to intent and usage. Singer is designed for streaming web scale data for real-time business critical applications at configurable, low and predictable latencies. 
The key difference would use case; application logs / APM (exceptions traces etc.) vs business logs (click stream etc.) and scale i.e. number of concurrent log streams. We haven't done comparison benchmarks with the mentioned technologies to see if there is a significant performance difference.

Also, Singer ships with its own logger that can be used by applications to log to file, in a format natively understood by Singer for forwarding logs to sink.

**Comment by billowqiu** [comment]
Very like scribed.
